name: farmapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Mapping
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_dragmarker: ^7.0.0

  # Networking & storage
  http: ^1.5.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0

  # Media & picker
  image_picker: ^1.2.0

  # AI (Gemini API)
  google_generative_ai: ^0.4.7

  # Location + date formatting
  geolocator: ^13.0.2
  geocoding: ^2.1.1
  intl: ^0.19.0
  http_parser: ^4.1.2
  path: ^1.9.1

  # Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Existing assets
    - assets/logo.png
    - assets/farm.jpg

    # Crop images for map_page.dart
    - media/
