# Generated by Django 5.2.5 on 2025-08-18 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dashboardpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pref', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardpreference',
            name='widgets',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_dt'],
                'indexes': [models.Index(fields=['user', 'start_dt'], name='accounts_ev_user_id_65c965_idx'), models.Index(fields=['user', 'end_dt'], name='accounts_ev_user_id_d041f6_idx')],
            },
        ),
    ]
