# Generated by Django 5.2.5 on 2025-09-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('image_path', models.URLField(blank=True, null=True)),
                ('spacing', models.FloatField(blank=True, null=True)),
                ('harvest_time', models.CharField(blank=True, max_length=100, null=True)),
                ('growth_stages', models.JSONField(blank=True, default=list)),
                ('pest_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
