# Generated by Django 5.2.5 on 2025-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growth_stages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvest_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image_path',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
