# Generated by Django 5.2.5 on 2025-09-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spacing', models.CharField(max_length=100)),
                ('harvest_time', models.CharField(max_length=100)),
                ('growth_stages', models.TextField(blank=True)),
                ('plant_type', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('watering_needs', models.CharField(blank=True, max_length=100)),
                ('sunlight_needs', models.CharField(blank=True, max_length=100)),
                ('planting_season', models.CharField(blank=True, max_length=100)),
                ('fertiliser_tips', models.TextField(blank=True)),
                ('pest_notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
            ],
        ),
    ]
