# Generated by Django 5.2.5 on 2025-09-05 07:41

import django.db.models.deletion
import plots.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('point', 'Point'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('polygon', 'Polygon')], max_length=16)),
                ('geometry', models.JSONField()),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('growth_stage', models.CharField(blank=True, default='', max_length=64)),
                ('planted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=plots.models.plot_media_path)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plots.plot')),
            ],
        ),
    ]
